name = "run-20260819-2034"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Run202608192034"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0-rc8"

[[lean_lib]]
name = "Run202608192034"
